export const mockData = [
  {
    id: 1,
    firstName: "Anandh",
    lastName: "Krishnan",
    email: "anandha2001@outlook.com",
    phone: "884848099",
    address: "KPN colony",
    city: "Cbe",
    state: "TN",
    country: "India",
    postalcode: "616300",
  },
  {
    id: 2,
    firstName: "Sanjay",
    lastName: "Kumar",
    email: "sanjay201@outlook.com",
    phone: "884848099",
    address: "Ramanathapuram",
    city: "Cbe",
    state: "TN",
    country: "India",
    postalcode: "616300",
  },
  {
    id: 3,
    firstName: "Mani",
    lastName: "K",
    email: "mani2001@outlook.com",
    phone: "884848099",
    address: "KSC colony",
    city: "Cbe",
    state: "TN",
    country: "India",
    postalcode: "616300",
  },
];

export const initialFormValues = {
  id: "",
  firstName: "",
  lastName: "",
  email: "",
  phone: "",
  address: "",
  city: "",
  state: "",
  country: "",
  postalcode: "",
};

export const formKeys = [
  { name: "firstName", label: "First name" },
  { name: "lastName", label: "Last name" },
  { name: "email", label: "Email" },
  { name: "phone", label: "Phone" },
  { name: "city", label: "City" },
  { name: "state", label: "State" },
  { name: "country", label: "Country" },
  { name: "postalcode", label: "Postal Code" },
  { name: "address", label: "Address", width: 12 },
];
