export const mockData = [
  {
    id: 1,
    firstName: "Anandh",
    lastName: "Krishnan",
    email: "anandha2001@outlook.com",
    phone: "884848099",
    address: "KPN colony",
    city: "Cbe",
    state: "TN",
    country: "India",
    postalcode: "616300",
  },
  {
    id: 2,
    firstName: "Sanjay",
    lastName: "Kumar",
    email: "sanjay201@outlook.com",
    phone: "884848099",
    address: "Ramanathapuram",
    city: "Cbe",
    state: "TN",
    country: "India",
    postalcode: "616300",
  },
  {
    id: 3,
    firstName: "Mani",
    lastName: "K",
    email: "mani2001@outlook.com",
    phone: "884848099",
    address: "KSC colony",
    city: "Cbe",
    state: "TN",
    country: "India",
    postalcode: "616300",
  },
];

export const initialFormValues = {
  id: "",
  firstName: "",
  lastName: "",
  email: "",
  phone: "",
  address: "",
  city: "",
  state: "",
  country: "",
  postalcode: "",
};
